In [2]:
import pandas as pd

In [6]:
import pandas as pd

data = [
    ["Alice", 25],
    ["Bob", 30],
    ["Charlie", 35]
]

df = pd.DataFrame(data, columns=["Name", "Age"])
df

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [11]:
data1={
    "name":["Abhishek","Ranjan","Choubey"],
     "age":[22,23,24]
      
}
df = pd.DataFrame(data1)
df

       name  age
0  Abhishek   22
1    Ranjan   23
2   Choubey   24

In [12]:
import numpy as np

In [14]:
arr=np.array([[1,2],[5,6]])
df=pd.DataFrame(arr,columns=["col1","col2"])
df

   col1  col2
0     1     2
1     5     6

In [16]:
df=pd.read_excel("data.xlsx")
df

       Name   School  Marks
0  Abhishek      PCS     98
1    Ranjan    ASPCS     97
2   Choubey  ASJMPCS     96
3  Divyansh      SVM     65
4     Aryan      LLS     92
5     Verma      DAV     99
6  Premdeep      DPS     88

In [19]:
df=pd.read_json("data.json")
df

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris
3    David   28    Berlin
4      Eva   22     Tokyo